//MISC
#macro TARGET_VISIBILITY 259200

//TCP MESSAGE CODES
	//Generic
#macro MSG_AUTHENTICATE 0
#macro MSG_UDPPORT 1
#macro MSG_JOINGAME 2
#macro MSG_ERROR 3

	//Game
#macro MSG_GAME_INFO 10
#macro MSG_GAME_BEGINSTATE 11
#macro MSG_GAME_JOINPLAYER 12
#macro MSG_GAME_PLAYERS 13

	//Player
#macro MSG_PLAYER_QUEUE 100
#macro MSG_PLAYER_HP 101
	
//UDP MESSAGE CODES
	//Generic
#macro MSG_UDPTEST 0
	
	//Player
#macro MSG_PLAYER_MOVEMENT 100
	
//APPEARANCE MAP KEYS
#macro APP_KEY_KIND 0
	
//KEY CODES
#macro KEY_P1_LEFT 0
#macro KEY_P1_RIGHT 1
#macro KEY_P1_FORWARD 2
#macro KEY_P1_BACKWARD 3
#macro KEY_P1_ATTACK 4
#macro KEY_P1_ATTACK2 5
#macro KEY_P1_RELOAD 6
#macro KEY_P1_FIREMODE 7
	
#macro KEY_P2_LEFT 100
#macro KEY_P2_RIGHT 101
#macro KEY_P2_FORWARD 102
#macro KEY_P2_BACKWARD 103
#macro KEY_P2_ATTACK 104
#macro KEY_P2_ATTACK2 105
#macro KEY_P2_RELOAD 106
#macro KEY_P2_FIREMODE 107
	
#macro KEY_P3_LEFT 200
#macro KEY_P3_RIGHT 201
#macro KEY_P3_FORWARD 202
#macro KEY_P3_BACKWARD 203
#macro KEY_P3_ATTACK 204
#macro KEY_P3_ATTACK2 205
#macro KEY_P3_RELOAD 206
#macro KEY_P3_FIREMODE 207
	
#macro KEYACTION_PRESS 0
#macro KEYACTION_HOLD 1
#macro KEYACTION_RELEASE 2
	
//ERROR CODES
#macro ERR_INVALIDUSER 0
#macro ERR_NONEXISTINGGAME 1
#macro ERR_GAMEFULL 2
	
//PLAYER TYPES
#macro PLYR_MAIN 0
#macro PLYR_COPY 1
#macro PLYR_FRESH 2
#macro PLYR_AI 2
	
//GAME STATES
#macro GSTATE_PREGAME 0
#macro GSTATE_GAME 1
	
//GAME MODES
#macro GMODE_TDM 0
#macro GMODE_FFA 1
	
//DOG ARMS ANIMATIONS
#macro ANIM_FISTS_IDLE 0
#macro ANIM_USP_IDLE 10
	
//WEAPON COMPONENT ATTRIBUTES
#macro ATTR_X 0
#macro ATTR_Y 1
#macro ATTR_SPR 2
#macro ATTR_IND 3
	
//WEAPON MODS
#macro MOD_SILENCER 0
	
// GUN FIRE MODES
#macro GUN_FMODE_SEMI 0
#macro GUN_FMODE_AUTO 1
	
//PHYSICS SHAPES
#macro PSHAPE_POLYGON 0
#macro PSHAPE_CIRCLE 1

//HEIGHT LEVELS
enum HL {
	low,
	high,
	air
}